"""Centralized configuration constants for the grid simulation."""

DEFAULT_GRID_WIDTH = 4
DEFAULT_GRID_HEIGHT = 4
DEFAULT_MAX_STEPS = 200
DEFAULT_INITIAL_FOOD = 1
DEFAULT_INITIAL_TRAPS = 1
DEFAULT_INITIAL_HEALTH = 100
DEFAULT_AGENT_IDS = ("agent_0",)

FOOD_REWARD = 10
TRAP_DAMAGE = 10
STEP_PENALTY = -1
